DROP TABLE IF EXISTS TBL_CARS;
 
CREATE TABLE TBL_CARS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  car_number VARCHAR(250) NOT NULL,
  car_model VARCHAR(250) NOT NULL,
);

DROP TABLE IF EXISTS TBL_DRIVERS;
 
CREATE TABLE TBL_DRIVERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  driver_name VARCHAR(250) NOT NULL,
  driver_mob VARCHAR(250) NOT NULL,
  driver_email varchar(250) DEFAULT NULL
);

DROP TABLE IF EXISTS TBL_CARS_DRIVERS;
 
CREATE TABLE TBL_CARS_DRIVERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  car_id VARCHAR(250) NOT NULL,
  driver_id VARCHAR(250) NOT NULL,
);

